# Generated by Django 2.1.8 on 2019-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='enshrine_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='enshrine_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='song_list',
            name='enshrine_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数量'),
        ),
    ]
