# Generated by Django 2.1.8 on 2019-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190907_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music', verbose_name='歌曲'),
        ),
    ]
