# Generated by Django 2.1.8 on 2019-09-07 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_music_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='user',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户歌曲'),
        ),
        migrations.AlterField(
            model_name='song_list',
            name='user_music_list',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='music_list', to=settings.AUTH_USER_MODEL, verbose_name='用户歌单'),
        ),
    ]
