# Generated by Django 2.1.8 on 2019-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190907_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='Song_List',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='Song_List', to='user.Song_List', verbose_name='歌单'),
        ),
    ]
