# Generated by Django 2.1.8 on 2019-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190907_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='note',
            field=models.CharField(max_length=128, verbose_name='歌手简介'),
        ),
    ]
