# Generated by Django 2.1.8 on 2019-09-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190907_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song_list',
            name='enshrine_num',
        ),
        migrations.AddField(
            model_name='song_list',
            name='play_num',
            field=models.IntegerField(default=0, null=True, verbose_name='播放数量'),
        ),
    ]
