# Generated by Django 2.1.8 on 2019-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190909_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='作者')),
            ],
            options={
                'verbose_name': '作者表',
                'verbose_name_plural': '作者表',
                'db_table': 'qzjg_author',
            },
        ),
        migrations.RemoveField(
            model_name='classify',
            name='Song_List',
        ),
        migrations.RemoveField(
            model_name='music',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='music',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song_list',
            name='user_music_list',
        ),
        migrations.AddField(
            model_name='singer',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.DeleteModel(
            name='Classify',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Song_List',
        ),
    ]
