# Generated by Django 2.1.8 on 2019-09-09 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190909_1120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20190904_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'qzjg_classify',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='歌曲名')),
                ('music', models.FileField(blank=True, null=True, upload_to='music', verbose_name='歌曲')),
                ('enshrine_num', models.IntegerField(default=0, null=True, verbose_name='收藏数量')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Author')),
                ('singer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Singer')),
                ('user', models.ManyToManyField(blank=True, db_constraint=False, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户歌曲')),
            ],
            options={
                'verbose_name': '歌曲表',
                'verbose_name_plural': '歌曲表',
                'db_table': 'qzjg_Music',
            },
        ),
        migrations.CreateModel(
            name='Song_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='歌单名称')),
                ('note', models.CharField(max_length=256, verbose_name='歌单简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='封面图')),
                ('play_num', models.IntegerField(default=0, null=True, verbose_name='播放数量')),
                ('user_music_list', models.ManyToManyField(blank=True, db_constraint=False, related_name='music_list', to=settings.AUTH_USER_MODEL, verbose_name='用户歌单')),
            ],
            options={
                'verbose_name': '歌单表',
                'verbose_name_plural': '歌单表',
                'db_table': 'song_list',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='orders',
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='classify',
            name='Song_List',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='Song_List', to='home.Song_List', verbose_name='歌单'),
        ),
    ]
