# Generated by Django 2.1.8 on 2019-09-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190909_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song_list',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='song_list', to='home.Song_List', verbose_name='歌单'),
        ),
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Singer', verbose_name='演唱者'),
        ),
    ]
