# Generated by Django 2.1.8 on 2019-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190909_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='link',
            field=models.CharField(max_length=64, verbose_name='导航地址'),
        ),
    ]
